PREFIX ub: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?x ?y ?z
WHERE {
  ?r a rdf:Statement .
  ?r rdf:subject ?x .
  ?r rdf:predicate ?y .
  ?r rdf:object ?z .
  ?r ub:yearOfAward "2017"^^xsd:integer .
}
