PREFIX ub: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?x
WHERE {
  <http://www.department14.university0.edu/graduateStudent106> ?sp <http://www.university1.edu> .
  ?sp rdf:singletonPropertyOf ub:undergraduateDegreeFrom .
  ?sp ub:graduationYear ?x .
}
