PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>

SELECT ?x ?y
WHERE {
  ?x a ub:Student .
  ?x ub:takesCourse ?y .
  ?y a ub:Course .
  <http://www.Department0.University0.edu/AssociateProfessor0> ub:teacherOf ?y .
}
