PREFIX ub: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>

SELECT ?x ?y ?z ?w
WHERE {
  ?x a ub:GraduateStudent .
  << ?x ub:undergraduateDegreeFrom ?y >> ub:yearOfAward ?w .
  ?x ub:memberOf ?z .
  ?y a ub:University .
  ?z a ub:Department .
  ?z ub:subOrganizationOf ?y .
}
